name: "Github Actions Controller"
description: "Pull & Update specific workflows into a repository"

inputs:
  testing_workflows:
    description: "Workflows for running testing of your code"
    default: "false"
  linting_workflows:
    description: "Workflows for linting your code"
    default: "false"
  build_workflows:
    description: "Workflows for building your code"
    default: "false"
  deployment_workflows:
    description: "Workflows for deploying your code"
    default: "false"
  github_token:
    description: "The target repo's github token"

runs:
  using: "composite"
  steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
      shell: bash

    - name: Run controller logic
      run: |
        bash "${{ github.action_path }}/src/scripts/pull_workflows.sh" \
          "${{ inputs.testing_workflows }}" \
          "${{ inputs.linting_workflows }}" \
          "${{ inputs.build_workflows }}" \
          "${{ inputs.deployment_workflows }}"
      env:
          GH_TOKEN: ${{ inputs.github_token }}
      shell: bash
