name: Deployment
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Lint codebase
              run: npm run lint
            - name: Test code
              run: npm run test
            - name: Build code
              run: npm run build
            - name: Deploy code
              run: echo "Deploying code..."
