name: Manual Token Refresh
on:
    workflow_dispatch:

jobs:
    refresh_token:
        runs-on: ubuntu-latest
        steps:
            - name: Generate new PAT token
              run: |
               gh auth login
               gh auth token --scopes repo --repo BenFielder/github-actions-controller --expires 1m --note "GH_AC_TOKEN"

